export const mockDataMonitor = [
  {
    id: 1,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 2,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 3,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 4,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 5,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 6,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 7,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 8,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 9,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i5',
    ram: 16,
    discohd: '1TB',
    estado: 'Inactivo',
  },
  {
    id: 10,
    lugar: 'CGD - Ministerio',
    cpucomputadora: 'Intel i7',
    ram: 16,
    discohd: '1TB',
    estado: 'Activo',
  },
  {
    id: 11,
    lugar: 'HPG - Ministerio',
    cpucomputadora: 'Intel i3',
    ram: 8,
    discohd: '500GB',
    estado: 'Activo',
  },
];
